import '../css/app.css';

import { createApp, h, type DefineComponent } from 'vue';
import { createInertiaApp } from '@inertiajs/vue3';
import { createPinia } from 'pinia';
import { i18n } from './i18n';
import { ZiggyVue, type Config as ZiggyConfig } from 'ziggy-js';
import { registerServiceWorker } from './pwa';
// Generated by `php artisan ziggy:generate`. Bundled and cache-busted with the
// app rather than inlined into every HTML response by @routes.
import { Ziggy } from './ziggy';
import { useSettingsStore } from './stores/settings';
import type { SharedProps } from './types/inertia';

const appName = import.meta.env.VITE_APP_NAME ?? 'Biertappen';

void createInertiaApp({
    title: (title) => (title ? `${title} · ${appName}` : appName),

    resolve: (name) => {
        const pages = import.meta.glob<DefineComponent>('./pages/**/*.vue');
        const page = pages[`./pages/${name}.vue`];

        if (!page) {
            throw new Error(`Inertia page not found: ${name}`);
        }

        return page();
    },

    setup({ el, App, props, plugin }) {
        const pinia = createPinia();

        const app = createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(pinia)
            .use(i18n)
            // The generated file is plain JS, so `methods` widens to string[];
            // the shape is correct by construction.
            .use(ZiggyVue, Ziggy as unknown as ZiggyConfig);

        /*
         * The server already decided the locale (account > session >
         * Accept-Language). Adopting its answer here — rather than picking one
         * independently — keeps <html lang>, server-rendered messages and the
         * client UI in agreement on the very first paint.
         */
        useSettingsStore(pinia).applyServerLocale(
            (props.initialPage.props as unknown as SharedProps).locale,
        );

        app.mount(el);
    },

    progress: {
        color: '#f5b301',
        showSpinner: false,
    },
});

registerServiceWorker();
